name: task_manager
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  responsive_builder: ^0.6.4
  auto_size_text: ^3.0.0
  context_menus: ^1.0.2
  mysql_manager: ^1.1.0
  uuid: ^3.0.7
  flutter_riverpod:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
